export const CONTRACT_ADDRESS = "0xEeef654Bc2B1D5287975B38E659B3ee0b348db15";

export const CONTRACT_ABI = [
  { name: "addRecord", type: "function", stateMutability: "nonpayable",
    inputs: [
      { name: "encHeartRate", type: "bytes32" },
      { name: "encOxygen", type: "bytes32" },
      { name: "encGlucose", type: "bytes32" },
      { name: "encTemp", type: "bytes32" },
      { name: "heartProof", type: "bytes" },
      { name: "oxygenProof", type: "bytes" },
      { name: "glucoseProof", type: "bytes" },
      { name: "tempProof", type: "bytes" },
      { name: "recordType", type: "string" },
    ], outputs: [] },
  { name: "grantAccess", type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "doctor", type: "address" }], outputs: [] },
  { name: "revokeAccess", type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "doctor", type: "address" }], outputs: [] },
  { name: "getRecordCount", type: "function", stateMutability: "view",
    inputs: [{ name: "patient", type: "address" }],
    outputs: [{ name: "", type: "uint256" }] },
  { name: "getRecord", type: "function", stateMutability: "view",
    inputs: [{ name: "patient", type: "address" }, { name: "index", type: "uint256" }],
    outputs: [
      { name: "heartRate", type: "bytes32" },
      { name: "oxygenLevel", type: "bytes32" },
      { name: "glucoseLevel", type: "bytes32" },
      { name: "temperature", type: "bytes32" },
      { name: "timestamp", type: "uint256" },
      { name: "recordType", type: "string" },
    ] },
  { name: "getGrantedDoctors", type: "function", stateMutability: "view",
    inputs: [{ name: "patient", type: "address" }],
    outputs: [{ name: "", type: "address[]" }] },
  { name: "hasAccess", type: "function", stateMutability: "view",
    inputs: [{ name: "patient", type: "address" }, { name: "doctor", type: "address" }],
    outputs: [{ name: "", type: "bool" }] },
  { name: "totalRecordsStored", type: "function", stateMutability: "view",
    inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { name: "RecordAdded", type: "event",
    inputs: [
      { name: "patient", type: "address", indexed: true },
      { name: "recordIndex", type: "uint256", indexed: true },
      { name: "recordType", type: "string", indexed: false },
      { name: "timestamp", type: "uint256", indexed: false },
    ] },
  { name: "AccessGranted", type: "event",
    inputs: [
      { name: "patient", type: "address", indexed: true },
      { name: "doctor", type: "address", indexed: true },
      { name: "timestamp", type: "uint256", indexed: false },
    ] },
  { name: "AccessRevoked", type: "event",
    inputs: [
      { name: "patient", type: "address", indexed: true },
      { name: "doctor", type: "address", indexed: true },
      { name: "timestamp", type: "uint256", indexed: false },
    ] },
] as const;