export const CONTRACT_ADDRESS = "0xbDb8E0Cb6Fc7e0857af7D2EAd33EcFb6CB9AfaDA";

export const CONTRACT_ABI = [
  { name: "addRecord", type: "function", stateMutability: "nonpayable",
    inputs: [
      { name: "encHeartRate", type: "bytes32" },
      { name: "encOxygen", type: "bytes32" },
      { name: "encGlucose", type: "bytes32" },
      { name: "encTemp", type: "bytes32" },
      { name: "heartProof", type: "bytes" },
      { name: "oxygenProof", type: "bytes" },
      { name: "glucoseProof", type: "bytes" },
      { name: "tempProof", type: "bytes" },
      { name: "recordType", type: "string" },
      { name: "metadata",      type: "string" },
    ], outputs: [] },
  { name: "grantAccess", type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "doctor", type: "address" }], outputs: [] },
  { name: "revokeAccess", type: "function", stateMutability: "nonpayable",
    inputs: [{ name: "doctor", type: "address" }], outputs: [] },
  { name: "getRecordCount", type: "function", stateMutability: "view",
    inputs: [{ name: "patient", type: "address" }],
    outputs: [{ name: "", type: "uint256" }] },
  { name: "getRecord", type: "function", stateMutability: "view",
    inputs: [{ name: "patient", type: "address" }, { name: "index", type: "uint256" }],
    outputs: [
      { name: "heartRate", type: "bytes32" },
      { name: "oxygenLevel", type: "bytes32" },
      { name: "glucoseLevel", type: "bytes32" },
      { name: "temperature", type: "bytes32" },
      { name: "timestamp", type: "uint256" },
      { name: "recordType", type: "string" },
    ] },
  { name: "getGrantedDoctors", type: "function", stateMutability: "view",
    inputs: [{ name: "patient", type: "address" }],
    outputs: [{ name: "", type: "address[]" }] },
  { name: "hasAccess", type: "function", stateMutability: "view",
    inputs: [{ name: "patient", type: "address" }, { name: "doctor", type: "address" }],
    outputs: [{ name: "", type: "bool" }] },
  { name: "totalRecordsStored", type: "function", stateMutability: "view",
    inputs: [], outputs: [{ name: "", type: "uint256" }] },
  { name: "getMyPatients", type: "function", stateMutability: "view",
  inputs: [{ name: "doctor", type: "address" }],
  outputs: [{ name: "", type: "address[]" }], },
  { name: "getRecordMetadata", type: "function", stateMutability: "view",
  inputs: [{ name: "patient", type: "address" }, { name: "index",   type: "uint256" }],
  outputs: [{ name: "", type: "string" }], },
  { name: "RecordAdded", type: "event",
    inputs: [
      { name: "patient", type: "address", indexed: true },
      { name: "recordIndex", type: "uint256", indexed: true },
      { name: "recordType", type: "string", indexed: false },
      { name: "timestamp", type: "uint256", indexed: false },
    ] },
  { name: "AccessGranted", type: "event",
    inputs: [
      { name: "patient", type: "address", indexed: true },
      { name: "doctor", type: "address", indexed: true },
      { name: "timestamp", type: "uint256", indexed: false },
    ] },
  { name: "AccessRevoked", type: "event",
    inputs: [
      { name: "patient", type: "address", indexed: true },
      { name: "doctor", type: "address", indexed: true },
      { name: "timestamp", type: "uint256", indexed: false },
    ] },
    {
  name: "registerAsDoctor",
  type: "function",
  stateMutability: "nonpayable",
  inputs: [],
  outputs: [],
},
{
  name: "isRegisteredDoctor",
  type: "function",
  stateMutability: "view",
  inputs: [{ name: "account", type: "address" }],
  outputs: [{ name: "", type: "bool" }],
},
{
  name: "DoctorRegistered",
  type: "event",
  inputs: [
    { name: "doctor", type: "address", indexed: true },
    { name: "timestamp", type: "uint256", indexed: false },
  ],
},
] as const;